name: monad-logger-aeson
version: '0.4.1.2'
github: "jship/monad-logger-aeson"
license: MIT
license-file: LICENSE.md
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: JSON logging using monad-logger interface
description: |
  @monad-logger-aeson@ provides structured JSON logging using @monad-logger@'s
  interface.

  Specifically, it is intended to be a (largely) drop-in replacement for
  @monad-logger@'s "Control.Monad.Logger.CallStack" module.
category: System

extra-source-files:
- package.yaml
- README.md
- LICENSE.md
- CHANGELOG.md

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - aeson >=1.5.2.0 && <2.3
  - base >=4.11.1.0 && <5
  - bytestring >=0.10.8.2 && <0.13.0.0
  - context >=0.2.0.0 && <0.3
  - exceptions >=0.10.0 && <0.11.0
  - fast-logger >=2.4.11 && <3.3.0
  - monad-logger >=0.3.30 && <0.4.0
  - text >=1.2.3.1 && <1.3.0.0 || >=2.0 && <2.2
  - time >=1.8.0.2 && <1.14
  - unordered-containers >=0.2.10.0 && <0.3.0.0
  source-dirs: library

tests:
  monad-logger-aeson-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - aeson >=1.5.2.0 && <2.3
    - aeson-diff >=1.1.0.5 && <1.2.0.0
    - base >=4.11.1.0 && <5
    - bytestring >=0.10.8.2 && <0.13.0.0
    - directory >=1.3.1.5 && <1.4.0.0
    - hspec >=2.7.9 && <2.12
    - monad-logger >=0.3.30 && <0.4.0
    - monad-logger-aeson
    - time >=1.8.0.2 && <1.14

executables:
  readme-example:
    source-dirs: app
    main: readme-example.hs
    dependencies:
    - aeson >=1.5.2.0 && <2.3
    - base >=4.11.1.0 && <5
    - monad-logger >=0.3.30 && <0.4.0
    - monad-logger-aeson
    - text >=1.2.3.1 && <1.3.0.0 || >=2.0 && <2.2
