name: monad-logger-aeson
version: '0.0.0.0'
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: monad-logger-aeson synopsis
description: monad-logger-aeson description
category: System

extra-source-files:
- package.yaml

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - aeson
  - base
  - bytestring
  - context >=0.2.0.0 && <0.3
  - exceptions
  - fast-logger
  - lifted-base
  - monad-control
  - monad-logger
  - text
  - time
  - transformers-base
  - unordered-containers
  source-dirs: library

tests:
  monad-logger-aeson-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - aeson
    - aeson-diff
    - base
    - bytestring
    - hspec
    - monad-logger
    - monad-logger-aeson
    - temporary
    - time

executables:
  monad-logger-aeson:
    source-dirs: app
    main: monad-logger-aeson.hs
    dependencies:
    - aeson
    - base
    - monad-logger
    - monad-logger-aeson
    - text
