name: monad-logger-aeson
version: '0.0.0.0'
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: monad-logger-aeson synopsis
description: monad-logger-aeson description
category: System

extra-source-files:
- package.yaml

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - aeson >=1.5.6.0 && <2.1.3.0
  - base >=4.14.3.0 && <5
  - bytestring >=0.10.12.0 && <0.12.0.0
  - context >=0.2.0.0 && <0.3
  - exceptions >=0.10.4 && <0.11.0
  - fast-logger >=3.0.5 && <3.2.0
  - monad-logger >=0.3.36 && <0.4.0
  - text >=1.2.4.1 && <1.3.0.0
  - time >=1.9.3 && <1.12.0.0
  - unordered-containers >=0.2.16.0 && <0.3.0.0
  source-dirs: library

tests:
  monad-logger-aeson-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - aeson >=1.5.6.0 && <2.1.3.0
    - aeson-diff >=1.1.0.10 && <1.2.0.0
    - base >=4.14.3.0 && <5
    - bytestring >=0.10.12.0 && <0.12.0.0
    - directory >=1.3.6.0 && <1.4.0.0
    - hspec >=2.7.10 && <2.10.0
    - monad-logger >=0.3.36 && <0.4.0
    - monad-logger-aeson
    - time >=1.9.3 && <1.12.0.0

executables:
  monad-logger-aeson:
    source-dirs: app
    main: monad-logger-aeson.hs
    dependencies:
    - aeson >=1.5.6.0 && <2.1.3.0
    - base >=4.14.3.0 && <5
    - monad-logger >=0.3.36 && <0.4.0
    - monad-logger-aeson
    - text >=1.2.4.1 && <1.3.0.0
