name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        resolver:
        - nightly # ghc-9.6.3
        - lts-21  # ghc-9.4.8
        - lts-20  # ghc-9.2.8
        - lts-19  # ghc-9.0.2
        - lts-18  # ghc-8.10.7
        - lts-16  # ghc-8.8.4
        - lts-14  # ghc-8.6.5
        - lts-12  # ghc-8.4.4

    steps:
    - uses: actions/checkout@v3
    - id: stack
      uses: freckle/stack-action@v4
      with:
        stack-yaml: stack/stack-${{ matrix.resolver }}.yaml
        stack-arguments: --bench --no-run-benchmarks --haddock --no-haddock-deps

  build-9_8:
    name: Haskell Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        ghc-version:
          - '9.8'
        cabal-version: ['3.10.2.0']
    steps:
      # Checkout
      - uses: actions/checkout@v3
        
      # Setup
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}

      - name: Cabal Bulid
        run: |
          (cat << EOF
          tests: True
          packages:
            monad-logger-aeson
          EOF
          ) > cabal.project
          cabal test all
