name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        resolver:
        - nightly # ghc-9.2.3
        - lts-19  # ghc-9.0.2
        - lts-18  # ghc-8.10.7
        - lts-16  # ghc-8.8.4
        - lts-14  # ghc-8.6.5
        - lts-12  # ghc-8.4.4

    steps:
    - uses: actions/checkout@v3
    - uses: freckle/stack-cache-action@v2
      with:
        prefix: v1/
        stack-yaml: stack-${{ matrix.resolver }}.yaml
    - uses: freckle/stack-action@v3
      with:
        stack-yaml: stack-${{ matrix.resolver }}.yaml
        stack-arguments: --bench --no-run-benchmarks --haddock --no-haddock-deps
