name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        resolver:
        - nightly-2022-05-05  # ghc-9.2.2
        - lts-19.6   # ghc-9.0.2
        - lts-18.28  # ghc-8.10.7
        - lts-16.31  # ghc-8.8.4

    steps:
    - uses: actions/checkout@v3
    - uses: freckle/stack-cache-action@v2
      with:
        prefix: v1/
        stack-yaml: stack-${{ matrix.resolver }}.yaml
    - uses: freckle/stack-action@v3
      with:
        stack-yaml: stack-${{ matrix.resolver }}.yaml
        stack-arguments: --bench --no-run-benchmarks --haddock --no-haddock-deps
